[[language]]
name = "cpp"
indent = {tab-width = 4, unit="    "}
formatter = { command = "clang-format" }
auto-format = true

[[language]]
name = "c"
indent = {tab-width = 4, unit="    "}

# [[language]]
# name = "python"
# auto-format = true
# roots = ["pyproject.toml"]
# language-server = {command = "pyright-langserver", args=["--stdio"]}
# config = {} # important line
[[language]]
name = "python"
language-servers = ["pylsp"]
auto-format = true

[language-server.pylsp.config.pylsp.plugins]
flake8 = {enabled = true}
autopep8 = {enabled = false}
yapf = {enabled = true}
mypy = {enabled = false}

# roots = ["pyproject.toml"]
# language-servers = ["ruff", "pyright"]

# [language-server.ruff]
# command = "ruff-lsp"
# config = { settings = { run = "onSave" } }

# [language-server.pyright]
# command = "pyright-langserver"
# args = ["--stdio"]

[language-server.mdpls]
command = "mdpls"
config = {markdown.preview.auto = true, markdown.preview.browser = "firefox"}

[[language]]
name = "markdown"
language-servers = ["mdpls"]

[[language]]
name = "prolog"
file-types = ["pl"]

[[language]]
name = "svelte"
indent = {tab-width=4, unit="    "}
language-servers = ["svelteserver", "typescript-language-server", "tailwindcss-language-server --stdio"]

[[language]]
name = "typescript"
indent = {tab-width=4, unit="    "}
language-servers = ["typescript-language-server"]
