[[language]]
name = "cpp"
indent = {tab-width = 4, unit="    "}

[[language]]
name = "c"
indent = {tab-width = 4, unit="    "}

[[language]]
name = "python"
auto-format = true
# roots = ["pyproject.toml"]
# language-server = {command = "pyright-langserver", args=["--stdio"]}
# config = {} # important line
