[[language]]
name = "cpp"
indent = {tab-width = 4, unit="    "}

[[language]]
name = "c"
indent = {tab-width = 4, unit="    "}

[[language]]
name = "python"
auto-format = true
# roots = ["pyproject.toml"]
# language-server = {command = "pyright-langserver", args=["--stdio"]}
# config = {} # important line

[language-server.mdpls]
command = "mdpls"
config = {markdown.preview.autu = true, markdown.preview.brewser = "firefox"}

[[language]]
name = "markdown"
language-servers = ["mdpls"]
