#!/bin/bash
# changeLuminosity

# Arbitrary but unique message tag
msgTag="myluminosity"

# Change the volume using alsa(might differ if you use pulseaudio)
xbacklight "$@" > /dev/null

# Query amixer for the current volume and whether or not the speaker is muted
luminosity="$(xbacklight -get)"
# Show the volume notification
dunstify -a "changeLuminosity" -u low -i luminosity -t 2000 -h string:x-dunst-stack-tag:$msgTag \
-h int:value:"$luminosity" "Luminosity: ${luminosity}%"

# Play the volume changed sound
canberra-gtk-play -i audio-volume-change -d "changeLuminosity"
